# Autogenerated by nbdev

d = { 'settings': {'branch': 'main', 'doc_baseurl': '/', 'doc_host': '', 'git_url': '', 'lib_path': 'udm_epic1'},
  'syms': { 'udm_epic1.augmentation.transforms': {},
            'udm_epic1.cli': {},
            'udm_epic1.dataset.pipeline': {},
            'udm_epic1.generators.sample_generator': {},
            'udm_epic1.generators.void_shapes': {},
            'udm_epic1.physics.beer_lambert': {}}}
