# AUTOGENERATED by nbdev — edit nbs/05_augmentation.ipynb instead
"""
Augmentation pipeline for UDM Epic 1.

CRITICAL DESIGN DECISION:
    Augmented images are NEVER saved to disk.
    Augmentation is applied at DataLoader time (training only).

    Why: Saving augmented images as separate training samples
    inflates the apparent dataset size, causes train/val leakage,
    and leads to overfitting on augmented artifacts.
    (This is a known issue with naive continuous learning systems.)

Two augmentation modes:
  1. GeometricAug  — flips, rotations (applied to image + mask jointly)
  2. PhotometricAug — brightness/contrast, blur (image only, mask unchanged)
  3. DomainShiftAug — simulates inter-machine artifacts (SAKI ring artifacts,
                       stitching seams) for cross-machine robustness
"""

from __future__ import annotations

import numpy as np
import cv2
from dataclasses import dataclass, field
from typing import Tuple, Optional
from scipy.ndimage import gaussian_filter


@dataclass
class AugConfig:
    """Augmentation configuration."""
    enabled: bool = True
    horizontal_flip: float = 0.5
    vertical_flip: float = 0.5
    rotate_90_prob: float = 0.3
    brightness_limit: float = 0.1
    contrast_limit: float = 0.1
    photometric_prob: float = 0.4
    blur_limit: Tuple[int, int] = (3, 5)
    blur_prob: float = 0.2
    # Domain shift augmentation
    domain_shift_enabled: bool = True
    ring_artifact_prob: float = 0.15
    ring_artifact_strength: Tuple[float, float] = (0.02, 0.08)
    stitch_seam_prob: float = 0.10


class AugmentationPipeline:
    """
    Training-time augmentation pipeline for synthetic X-ray void images.

    All operations are applied to float32 images normalized to [0, 1].
    Geometric operations are applied jointly to image and mask.
    Photometric and domain-shift operations are applied to image only.

    Usage
    -----
    >>> aug = AugmentationPipeline(AugConfig())
    >>> img_aug, mask_aug = aug(image_float32, mask_uint8)

    The pipeline is deterministic given the same rng state — pass a
    seeded rng for reproducible augmentation during debugging.
    """

    def __init__(self, config: AugConfig, rng: Optional[np.random.Generator] = None):
        self.cfg = config
        self.rng = rng or np.random.default_rng()

    def __call__(
        self, image: np.ndarray, mask: np.ndarray
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Apply full augmentation pipeline.

        Args:
            image: float32 [H, W] in [0, 1]
            mask:  uint8  [H, W] in {0, 255}

        Returns:
            Augmented (image, mask) pair with same dtypes.
        """
        if not self.cfg.enabled:
            return image, mask

        img = image.copy()
        msk = mask.copy()

        # Geometric (joint)
        img, msk = self._geometric(img, msk)

        # Photometric (image only)
        img = self._photometric(img)

        # Domain shift (image only — simulates cross-machine artifacts)
        if self.cfg.domain_shift_enabled:
            img = self._domain_shift(img)

        img = np.clip(img, 0.0, 1.0).astype(np.float32)
        return img, msk

    # ─── Geometric ────────────────────────────────────────────────────────────

    def _geometric(
        self, image: np.ndarray, mask: np.ndarray
    ) -> Tuple[np.ndarray, np.ndarray]:
        # Horizontal flip
        if self.rng.random() < self.cfg.horizontal_flip:
            image = np.fliplr(image)
            mask = np.fliplr(mask)

        # Vertical flip
        if self.rng.random() < self.cfg.vertical_flip:
            image = np.flipud(image)
            mask = np.flipud(mask)

        # 90° rotation (0, 90, 180, 270)
        if self.rng.random() < self.cfg.rotate_90_prob:
            k = int(self.rng.integers(1, 4))
            image = np.rot90(image, k)
            mask = np.rot90(mask, k)

        return image, mask

    # ─── Photometric ──────────────────────────────────────────────────────────

    def _photometric(self, image: np.ndarray) -> np.ndarray:
        if self.rng.random() > self.cfg.photometric_prob:
            return image

        # Brightness: additive offset
        b_shift = self.rng.uniform(-self.cfg.brightness_limit, self.cfg.brightness_limit)
        image = image + b_shift

        # Contrast: multiplicative around mean
        c_factor = 1.0 + self.rng.uniform(-self.cfg.contrast_limit, self.cfg.contrast_limit)
        mean_val = image.mean()
        image = (image - mean_val) * c_factor + mean_val

        # Gaussian blur (simulates detector defocus)
        if self.rng.random() < self.cfg.blur_prob:
            sigma = self.rng.uniform(0.3, 1.2)
            image = gaussian_filter(image, sigma=sigma)

        return image

    # ─── Domain Shift Augmentation ────────────────────────────────────────────

    def _domain_shift(self, image: np.ndarray) -> np.ndarray:
        """
        Simulate cross-machine visual artifacts to improve domain robustness.

        These augmentations teach the model to be invariant to:
          - SAKI ring artifacts (concentric circular patterns)
          - Stitching seam artifacts (linear intensity discontinuities)

        This is a key technique for P1→P2 transition readiness.
        """
        # Ring artifact (SAKI 3Xi-style — from detector element non-uniformity)
        if self.rng.random() < self.cfg.ring_artifact_prob:
            image = self._add_ring_artifact(image)

        # Stitching seam (SAKI tomographic slice boundaries)
        if self.rng.random() < self.cfg.stitch_seam_prob:
            image = self._add_stitch_seam(image)

        return image

    def _add_ring_artifact(self, image: np.ndarray) -> np.ndarray:
        """
        Add concentric ring artifact centered at a random point.

        Simulates SAKI ring artifacts caused by non-uniform detector
        element response in CT reconstruction.
        """
        H, W = image.shape[:2]
        strength = self.rng.uniform(*self.cfg.ring_artifact_strength)

        # Random ring center (often near image center in real SAKI data)
        cx = self.rng.uniform(0.3 * W, 0.7 * W)
        cy = self.rng.uniform(0.3 * H, 0.7 * H)

        # Distance map from center
        y_idx, x_idx = np.ogrid[:H, :W]
        dist = np.sqrt((x_idx - cx)**2 + (y_idx - cy)**2)

        # Ring pattern: sinusoidal modulation of distance
        ring_freq = self.rng.uniform(0.05, 0.2)  # rings per pixel
        ring_phase = self.rng.uniform(0, 2 * np.pi)
        ring_pattern = strength * np.sin(2 * np.pi * ring_freq * dist + ring_phase)

        # Attenuate ring strength at large distances
        max_dist = np.sqrt((H/2)**2 + (W/2)**2)
        attenuation = np.exp(-dist / (max_dist * 0.5))
        ring_pattern *= attenuation

        return image + ring_pattern.astype(np.float32)

    def _add_stitch_seam(self, image: np.ndarray) -> np.ndarray:
        """
        Add a linear stitching seam artifact.

        Simulates the intensity discontinuity at tomographic slice
        boundaries in SAKI stitched images.
        """
        H, W = image.shape[:2]
        strength = self.rng.uniform(0.01, 0.04)

        # Random horizontal or vertical seam
        if self.rng.random() < 0.5:
            # Horizontal seam
            y_pos = int(self.rng.integers(H // 4, 3 * H // 4))
            seam_width = int(self.rng.integers(2, 6))
            y0 = max(0, y_pos - seam_width // 2)
            y1 = min(H, y_pos + seam_width // 2)
            artifact = np.zeros((H, W), dtype=np.float32)
            artifact[y0:y1, :] = strength * self.rng.choice([-1, 1])
            # Soften seam edges
            artifact = gaussian_filter(artifact, sigma=1.5)
        else:
            # Vertical seam
            x_pos = int(self.rng.integers(W // 4, 3 * W // 4))
            seam_width = int(self.rng.integers(2, 6))
            x0 = max(0, x_pos - seam_width // 2)
            x1 = min(W, x_pos + seam_width // 2)
            artifact = np.zeros((H, W), dtype=np.float32)
            artifact[:, x0:x1] = strength * self.rng.choice([-1, 1])
            artifact = gaussian_filter(artifact, sigma=1.5)

        return image + artifact
