# AUTOGENERATED by nbdev — edit nbs/01_physics.ipynb instead
"""
Physics-based X-ray image synthesis using the Beer-Lambert law.

Beer-Lambert: I = I0 * exp(-mu * t)

Where:
    I   = transmitted intensity (what the detector sees)
    I0  = incident X-ray intensity
    mu  = linear attenuation coefficient of the material
    t   = material thickness along the beam path

Voids are air pockets (mu_void ≈ 0), so they appear BRIGHTER than
surrounding solder material in transmission X-ray images.
This is the physical basis for all void contrast in MatriX and SAKI images.
"""

from __future__ import annotations

import numpy as np
from dataclasses import dataclass, field
from typing import Tuple, Optional
import cv2
from scipy.ndimage import gaussian_filter


@dataclass
class BeerLambertConfig:
    """Configuration for Beer-Lambert physics simulation."""
    mu_background_range: Tuple[float, float] = (0.8, 1.2)
    mu_void: float = 0.0
    thickness_range: Tuple[float, float] = (0.3, 1.0)
    apply_sft_correction: bool = True
    sft_sigma: float = 15.0
    poisson_noise: bool = True
    poisson_scale: float = 0.02
    gaussian_sigma_range: Tuple[float, float] = (0.5, 2.5)
    salt_pepper_prob: float = 0.001
    low_percentile: float = 2.0
    high_percentile: float = 98.0


class BeerLambertSimulator:
    """
    Simulates X-ray transmission images using Beer-Lambert physics.

    This is the core physics engine for Epic 1. It generates realistic
    X-ray intensity maps where voids produce localized brightness increases
    due to reduced attenuation (air has mu ≈ 0 vs solder mu > 0).

    Key insight for semiconductor X-ray:
        - Solder joint: high mu → low transmitted intensity → dark
        - Void (air): mu ≈ 0 → high transmitted intensity → bright
        - Contrast = exp(-mu_void * t) / exp(-mu_solder * t)
                   = exp(mu_solder * t)  → always > 1

    Nordson MatriX specifics:
        - 16-bit detector, Dynamic Planar CT
        - SFT (Structured Flat-field correction) removes background gradient
        - We simulate SFT by subtracting a large-sigma Gaussian blur

    SAKI 3Xi-M110 specifics:
        - Hundreds of stitched tomographic slices
        - Different noise texture (ring artifacts possible)
        - Handled via domain-shift augmentation, not physics model change
    """

    def __init__(self, config: BeerLambertConfig, rng: Optional[np.random.Generator] = None):
        self.cfg = config
        self.rng = rng or np.random.default_rng(42)

    # ─── Background ──────────────────────────────────────────────────────────

    def generate_background_field(self, height: int, width: int) -> np.ndarray:
        """
        Generate a spatially varying attenuation background.

        Models: non-uniform solder thickness, substrate density gradients,
        and beam hardening effects across the field of view.

        Returns float32 array in [0, 1], representing normalized transmitted
        intensity BEFORE void insertion.
        """
        # Spatially varying mu (material non-uniformity)
        mu_mean = self.rng.uniform(*self.cfg.mu_background_range)
        mu_field = mu_mean + 0.05 * self._perlin_like_noise(height, width)

        # Spatially varying thickness (solder volume variation)
        t_mean = self.rng.uniform(*self.cfg.thickness_range)
        t_field = t_mean + 0.08 * self._perlin_like_noise(height, width, scale=0.3)
        t_field = np.clip(t_field, 0.1, 1.0)

        # Beer-Lambert: transmitted intensity
        I0 = 1.0  # normalized incident intensity
        I = I0 * np.exp(-mu_field * t_field)

        # Add detector noise
        I = self._add_noise(I)

        # Simulate SFT background correction (MatriX-style)
        if self.cfg.apply_sft_correction:
            I = self._apply_sft_correction(I)

        return I.astype(np.float32)

    def _perlin_like_noise(
        self, height: int, width: int, scale: float = 1.0, octaves: int = 4
    ) -> np.ndarray:
        """
        Multi-octave smooth noise field (Perlin-like).
        Used to simulate spatial non-uniformity in solder thickness and density.
        """
        noise = np.zeros((height, width), dtype=np.float64)
        amplitude = 1.0
        frequency = 1.0
        for _ in range(octaves):
            # Random base noise at current scale
            base = self.rng.standard_normal((height, width))
            sigma = max(1.0, min(height, width) / (8.0 * frequency * scale))
            smoothed = gaussian_filter(base, sigma=sigma)
            noise += amplitude * smoothed
            amplitude *= 0.5
            frequency *= 2.0
        # Normalize to [-1, 1]
        noise_range = noise.max() - noise.min()
        if noise_range > 1e-9:
            noise = 2.0 * (noise - noise.min()) / noise_range - 1.0
        return noise

    def _apply_sft_correction(self, image: np.ndarray) -> np.ndarray:
        """
        Simulate Nordson MatriX SFT (Structured Flat-field) background removal.

        SFT estimates the slowly-varying background using a large Gaussian blur
        and subtracts it, leaving only the high-frequency content (the joints).
        We add back a neutral offset so values stay positive.
        """
        background_estimate = gaussian_filter(image, sigma=self.cfg.sft_sigma)
        corrected = image - background_estimate + 0.5
        return corrected

    def _add_noise(self, image: np.ndarray) -> np.ndarray:
        """Add realistic detector noise: Poisson (shot noise) + Gaussian (readout)."""
        noisy = image.copy()

        # Poisson / shot noise — proportional to signal level
        if self.cfg.poisson_noise:
            shot = self.rng.normal(0, self.cfg.poisson_scale * np.sqrt(np.abs(noisy) + 1e-6))
            noisy += shot

        # Gaussian readout noise
        sigma = self.rng.uniform(*self.cfg.gaussian_sigma_range) / 255.0
        noisy += self.rng.normal(0, sigma, size=noisy.shape)

        # Salt & pepper (dead/hot pixels)
        if self.cfg.salt_pepper_prob > 0:
            sp_mask = self.rng.random(noisy.shape) < self.cfg.salt_pepper_prob
            noisy[sp_mask] = self.rng.choice([0.0, 1.0], size=sp_mask.sum())

        return noisy

    # ─── Void Insertion ───────────────────────────────────────────────────────

    def insert_void(
        self,
        background: np.ndarray,
        void_mask: np.ndarray,
        contrast: float,
        edge_sigma: float = 1.0,
    ) -> np.ndarray:
        """
        Insert a void into a background image using Beer-Lambert physics.

        The void region has mu_void = 0, so its transmitted intensity is:
            I_void = I0 * exp(-mu_void * t) = I0  (full transmission)

        The contrast parameter scales how bright the void appears relative
        to surrounding material. Higher contrast = more visible void.

        Args:
            background:  float32 [H, W] normalized background image
            void_mask:   uint8 [H, W] binary mask (255=void, 0=background)
            contrast:    void brightness boost in [0, 1] range
            edge_sigma:  Gaussian blur on void boundary for realism

        Returns:
            float32 [H, W] image with void inserted
        """
        result = background.copy()
        mask_f = void_mask.astype(np.float32) / 255.0

        # Soften void edges (real voids have gradual boundaries due to partial volume)
        if edge_sigma > 0.3:
            mask_soft = gaussian_filter(mask_f, sigma=edge_sigma)
        else:
            mask_soft = mask_f

        # Compute void brightness: local background + contrast boost
        local_bg_mean = np.mean(background[void_mask > 127]) if void_mask.any() else 0.5
        void_brightness = np.clip(local_bg_mean + contrast, 0.0, 1.0)

        # Blend: result = background * (1 - mask) + void_brightness * mask
        result = background * (1.0 - mask_soft) + void_brightness * mask_soft

        return result.astype(np.float32)

    # ─── Normalization ────────────────────────────────────────────────────────

    def percentile_normalize(
        self,
        image: np.ndarray,
        low: Optional[float] = None,
        high: Optional[float] = None,
    ) -> np.ndarray:
        """
        p2/p98 percentile normalization.

        This is the exact normalization that gets baked into the ONNX graph.
        Robust to outlier pixel values (hot pixels, ring artifacts).

        Args:
            image: float32 array, any range
            low:   lower percentile (default: cfg.low_percentile)
            high:  upper percentile (default: cfg.high_percentile)

        Returns:
            float32 array in [0.0, 1.0]
        """
        low = low or self.cfg.low_percentile
        high = high or self.cfg.high_percentile
        p_low = np.percentile(image, low)
        p_high = np.percentile(image, high)
        denom = p_high - p_low
        if denom < 1e-9:
            return np.zeros_like(image)
        normalized = (image - p_low) / denom
        return np.clip(normalized, 0.0, 1.0).astype(np.float32)

    def to_uint16(self, image_float: np.ndarray) -> np.ndarray:
        """Convert normalized float32 [0,1] → uint16 [0, 65535] for 16-bit PNG storage."""
        return (np.clip(image_float, 0.0, 1.0) * 65535).astype(np.uint16)

    def to_uint8(self, image_float: np.ndarray) -> np.ndarray:
        """Convert normalized float32 [0,1] → uint8 [0, 255] for visualization."""
        return (np.clip(image_float, 0.0, 1.0) * 255).astype(np.uint8)
