# AUTOGENERATED by nbdev — edit nbs/03_generator.ipynb instead
"""
Core synthetic sample generator.

Composes:
  1. BeerLambertSimulator  → background field
  2. VoidShapeGenerator    → void masks
  3. Augmentation pipeline → domain-shift robustness

One call to SyntheticSampleGenerator.generate() produces:
  - image: np.ndarray uint16 [H, W]  (16-bit, ready for PNG save)
  - mask:  np.ndarray uint8  [H, W]  (binary, 255=void)
  - meta:  dict  (void count, shapes, area fractions, etc.)

Design note on augmentation:
  Augmented images are NOT saved to disk. Only the base synthetic
  image+mask pair is persisted. Augmentation is applied at training
  time via the DataLoader. This avoids the overfitting trap of saving
  augmented versions as separate training samples.
"""

from __future__ import annotations

import numpy as np
import cv2
from dataclasses import dataclass, field, asdict
from typing import List, Optional, Tuple, Dict, Any
from pathlib import Path

from udm_epic1.physics.beer_lambert import BeerLambertSimulator, BeerLambertConfig
from udm_epic1.generators.void_shapes import VoidShapeGenerator, VoidGeometry


@dataclass
class SampleMeta:
    """Metadata for a single generated synthetic sample."""
    image_id: str
    height: int
    width: int
    n_voids: int
    void_geometries: List[Dict[str, Any]] = field(default_factory=list)
    total_void_area_fraction: float = 0.0
    has_voids: bool = False
    background_mu_mean: float = 0.0
    split: str = "train"

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class GeneratorConfig:
    """Full configuration for the synthetic sample generator."""
    height: int = 512
    width: int = 512
    min_area_fraction: float = 0.001
    max_area_fraction: float = 0.25
    void_count_range: Tuple[int, int] = (0, 8)
    empty_image_fraction: float = 0.15
    allow_overlap: bool = False
    min_void_separation: int = 8
    shape_weights: Dict[str, float] = field(default_factory=lambda: {
        "ellipse": 0.45,
        "irregular_blob": 0.35,
        "elongated": 0.12,
        "cluster": 0.08,
    })
    bit_depth: int = 16
    physics: BeerLambertConfig = field(default_factory=BeerLambertConfig)


class SyntheticSampleGenerator:
    """
    Generates one (image, mask, meta) triplet per call.

    This is the atomic unit of Epic 1. The pipeline runner calls this
    in parallel via joblib to achieve 17× speed vs manual annotation.

    Example
    -------
    >>> cfg = GeneratorConfig(height=512, width=512)
    >>> gen = SyntheticSampleGenerator(cfg, seed=42)
    >>> image, mask, meta = gen.generate(image_id="sample_0001")
    >>> assert image.dtype == np.uint16
    >>> assert mask.dtype == np.uint8
    >>> assert mask.max() in (0, 255)
    """

    def __init__(self, config: GeneratorConfig, seed: int = 42):
        self.cfg = config
        self.rng = np.random.default_rng(seed)
        self.physics = BeerLambertSimulator(config.physics, rng=self.rng)
        self.shapes = VoidShapeGenerator(rng=self.rng)

    def generate(
        self,
        image_id: str = "sample",
        split: str = "train",
        background: Optional[np.ndarray] = None,
    ) -> Tuple[np.ndarray, np.ndarray, SampleMeta]:
        """
        Generate one synthetic (image, mask, meta) triplet.

        Args:
            image_id:    Unique identifier string for this sample
            split:       'train' | 'val' | 'test'
            background:  Optional real background image (float32 [H, W]).
                         If None, a synthetic Beer-Lambert background is generated.

        Returns:
            image: uint16 [H, W]  — 16-bit X-ray image
            mask:  uint8  [H, W]  — binary segmentation mask (255=void)
            meta:  SampleMeta     — full generation metadata
        """
        H, W = self.cfg.height, self.cfg.width

        # Step 1: Generate or use provided background
        if background is not None:
            bg = self._preprocess_background(background, H, W)
        else:
            bg = self.physics.generate_background_field(H, W)

        # Step 2: Decide number of voids
        is_empty = self.rng.random() < self.cfg.empty_image_fraction
        if is_empty:
            n_voids = 0
        else:
            lo, hi = self.cfg.void_count_range
            n_voids = int(self.rng.integers(max(1, lo), hi + 1))

        # Step 3: Generate voids
        composite = bg.copy()
        combined_mask = np.zeros((H, W), dtype=np.uint8)
        placed_masks: List[np.ndarray] = []
        placed_geometries: List[Dict] = []
        total_void_area = 0.0

        for _ in range(n_voids):
            geom = self.shapes.sample_geometry(
                height=H,
                width=W,
                min_area_fraction=self.cfg.min_area_fraction,
                max_area_fraction=self.cfg.max_area_fraction,
                shape_weights=self.cfg.shape_weights,
                existing_masks=placed_masks if not self.cfg.allow_overlap else None,
                min_separation=self.cfg.min_void_separation,
            )
            if geom is None:
                continue  # Could not place without overlap

            void_mask = self.shapes.generate(H, W, geom)
            composite = self.physics.insert_void(
                background=composite,
                void_mask=void_mask,
                contrast=geom.contrast,
                edge_sigma=geom.edge_sigma,
            )

            # Accumulate mask (union)
            combined_mask = np.maximum(combined_mask, void_mask)
            placed_masks.append(void_mask)

            actual_area = (void_mask > 127).sum() / (H * W)
            total_void_area += actual_area
            placed_geometries.append({
                "cx": geom.cx, "cy": geom.cy,
                "shape": geom.shape,
                "area_fraction": round(actual_area, 5),
                "contrast": round(geom.contrast, 4),
                "edge_sigma": round(geom.edge_sigma, 3),
            })

        # Step 4: Percentile normalize → [0, 1] float
        normalized = self.physics.percentile_normalize(composite)

        # Step 5: Convert to target bit depth
        if self.cfg.bit_depth == 16:
            image_out = self.physics.to_uint16(normalized)
        else:
            image_out = self.physics.to_uint8(normalized)

        # Step 6: Build metadata
        meta = SampleMeta(
            image_id=image_id,
            height=H,
            width=W,
            n_voids=len(placed_geometries),
            void_geometries=placed_geometries,
            total_void_area_fraction=round(total_void_area, 5),
            has_voids=len(placed_geometries) > 0,
            background_mu_mean=float(np.mean(bg)),
            split=split,
        )

        return image_out, combined_mask, meta

    def _preprocess_background(
        self, bg: np.ndarray, H: int, W: int
    ) -> np.ndarray:
        """
        Preprocess a real background image for void insertion.

        - Resize to target resolution
        - Convert to float32 in [0, 1]
        - Apply percentile normalization for consistency
        """
        if bg.shape[:2] != (H, W):
            bg = cv2.resize(bg, (W, H), interpolation=cv2.INTER_LINEAR)

        if bg.dtype == np.uint16:
            bg = bg.astype(np.float32) / 65535.0
        elif bg.dtype == np.uint8:
            bg = bg.astype(np.float32) / 255.0
        else:
            bg = bg.astype(np.float32)

        return self.physics.percentile_normalize(bg)
