# AUTOGENERATED by nbdev — edit nbs/02_void_shapes.ipynb instead
"""
Void shape generators for synthetic X-ray void synthesis.

Real solder voids come in 4 primary morphological classes:
  1. Elliptical  — most common, near-spherical voids from trapped gas
  2. Irregular blob — non-convex, coalesced voids
  3. Elongated   — high aspect-ratio voids along pad edges
  4. Cluster     — multiple micro-voids in proximity (looks like one region)

Each generator returns a binary mask (uint8, 255=void) of the same
(height, width) as the image, positioned at a specified center.
"""

from __future__ import annotations

import numpy as np
import cv2
from dataclasses import dataclass
from typing import Tuple, List, Optional
from scipy.ndimage import gaussian_filter


@dataclass
class VoidGeometry:
    """Describes the geometry of a single synthetic void."""
    cx: int           # center x
    cy: int           # center y
    area_fraction: float  # fraction of image area
    shape: str        # 'ellipse' | 'irregular_blob' | 'elongated' | 'cluster'
    contrast: float   # brightness boost in [0,1]
    edge_sigma: float # boundary blur sigma


class VoidShapeGenerator:
    """
    Generates binary void masks for all 4 morphological classes.

    Design principles:
      - All shapes are parameterized by area_fraction (not pixel size)
        so the generator is resolution-independent.
      - Edges are intentionally NOT hard binary — real voids have
        partial-volume effects at boundaries (sub-pixel attenuation).
      - The rng is always passed in to ensure full reproducibility.
    """

    def __init__(self, rng: Optional[np.random.Generator] = None):
        self.rng = rng or np.random.default_rng(42)

    def generate(
        self,
        height: int,
        width: int,
        geometry: VoidGeometry,
    ) -> np.ndarray:
        """
        Dispatch to the correct shape generator.

        Returns uint8 mask [H, W], values 0 or 255.
        """
        dispatch = {
            "ellipse": self._ellipse,
            "irregular_blob": self._irregular_blob,
            "elongated": self._elongated,
            "cluster": self._cluster,
        }
        fn = dispatch.get(geometry.shape, self._ellipse)
        return fn(height, width, geometry)

    # ─── Shape Implementations ────────────────────────────────────────────────

    def _ellipse(self, H: int, W: int, g: VoidGeometry) -> np.ndarray:
        """
        Elliptical void — most common morphology in BGA solder joints.

        Radius derived from area_fraction: area = pi*a*b, so we set
        a = r * aspect, b = r / aspect where r = sqrt(area / pi).
        """
        mask = np.zeros((H, W), dtype=np.uint8)
        total_px = H * W
        area_px = g.area_fraction * total_px

        r = np.sqrt(area_px / np.pi)
        aspect = self.rng.uniform(0.5, 2.0)
        axes = (
            max(2, int(r * aspect)),
            max(2, int(r / aspect)),
        )
        angle = self.rng.integers(0, 180)
        cv2.ellipse(mask, (g.cx, g.cy), axes, angle, 0, 360, 255, -1)
        return mask

    def _irregular_blob(self, H: int, W: int, g: VoidGeometry) -> np.ndarray:
        """
        Irregular blob — coalesced or non-convex voids.

        Generated by:
          1. Start with a base ellipse
          2. Add random polygon perturbation around circumference
          3. Smooth with gaussian to get organic shape
        """
        mask = np.zeros((H, W), dtype=np.uint8)
        total_px = H * W
        area_px = g.area_fraction * total_px
        r = max(4, np.sqrt(area_px / np.pi))

        # Generate random polygon with perturbed radii
        n_pts = self.rng.integers(8, 20)
        angles = np.linspace(0, 2 * np.pi, n_pts, endpoint=False)
        # Random radial perturbation: ±30% of base radius
        radii = r * (1.0 + self.rng.uniform(-0.3, 0.3, size=n_pts))
        pts = np.array([
            [int(g.cx + radii[i] * np.cos(a)),
             int(g.cy + radii[i] * np.sin(a))]
            for i, a in enumerate(angles)
        ], dtype=np.int32)

        cv2.fillPoly(mask, [pts], 255)

        # Smooth to remove sharp polygon corners
        mask_f = gaussian_filter(mask.astype(np.float32), sigma=r * 0.15)
        mask = (mask_f > 64).astype(np.uint8) * 255
        return mask

    def _elongated(self, H: int, W: int, g: VoidGeometry) -> np.ndarray:
        """
        Elongated void — high aspect ratio, common along pad edges.

        Aspect ratio in [3, 8], oriented randomly.
        """
        mask = np.zeros((H, W), dtype=np.uint8)
        total_px = H * W
        area_px = g.area_fraction * total_px

        aspect = self.rng.uniform(3.0, 8.0)
        # area = pi * a * b, a = aspect * b => area = pi * aspect * b^2
        b = max(2, int(np.sqrt(area_px / (np.pi * aspect))))
        a = max(4, int(aspect * b))
        axes = (a, b)
        angle = self.rng.integers(0, 180)
        cv2.ellipse(mask, (g.cx, g.cy), axes, angle, 0, 360, 255, -1)
        return mask

    def _cluster(self, H: int, W: int, g: VoidGeometry) -> np.ndarray:
        """
        Void cluster — multiple micro-voids in proximity.

        Simulates coalescence-in-progress: 3–7 small ellipses
        distributed around the center point within a cluster radius.
        """
        mask = np.zeros((H, W), dtype=np.uint8)
        total_px = H * W
        area_px = g.area_fraction * total_px

        n_sub = self.rng.integers(3, 8)
        sub_area = area_px / n_sub
        r_sub = max(2, np.sqrt(sub_area / np.pi))

        # Cluster spread radius
        spread = r_sub * self.rng.uniform(1.5, 3.0)

        for _ in range(n_sub):
            # Random offset from cluster center
            dx = int(self.rng.uniform(-spread, spread))
            dy = int(self.rng.uniform(-spread, spread))
            cx = np.clip(g.cx + dx, 0, W - 1)
            cy = np.clip(g.cy + dy, 0, H - 1)

            aspect = self.rng.uniform(0.6, 1.8)
            axes = (
                max(1, int(r_sub * aspect)),
                max(1, int(r_sub / aspect)),
            )
            angle = self.rng.integers(0, 180)
            cv2.ellipse(mask, (int(cx), int(cy)), axes, angle, 0, 360, 255, -1)

        return mask

    # ─── Placement ────────────────────────────────────────────────────────────

    def sample_geometry(
        self,
        height: int,
        width: int,
        min_area_fraction: float,
        max_area_fraction: float,
        shape_weights: Optional[dict] = None,
        existing_masks: Optional[List[np.ndarray]] = None,
        min_separation: int = 8,
        max_attempts: int = 50,
    ) -> Optional[VoidGeometry]:
        """
        Sample a random VoidGeometry that doesn't overlap existing voids.

        Returns None if no valid placement found after max_attempts.
        """
        if shape_weights is None:
            shape_weights = {
                "ellipse": 0.45,
                "irregular_blob": 0.35,
                "elongated": 0.12,
                "cluster": 0.08,
            }

        shapes = list(shape_weights.keys())
        weights = np.array([shape_weights[s] for s in shapes])
        weights = weights / weights.sum()

        area_frac = self.rng.uniform(min_area_fraction, max_area_fraction)
        shape = self.rng.choice(shapes, p=weights)
        contrast = self.rng.uniform(0.08, 0.35)
        edge_sigma = self.rng.uniform(0.5, 2.0)

        # Estimate void radius for placement margin
        total_px = height * width
        r_est = max(4, int(np.sqrt(area_frac * total_px / np.pi) * 1.5))
        margin = r_est + min_separation

        for _ in range(max_attempts):
            cx = int(self.rng.integers(margin, max(margin + 1, width - margin)))
            cy = int(self.rng.integers(margin, max(margin + 1, height - margin)))

            if existing_masks:
                # Check overlap with all existing void masks
                collision = False
                for em in existing_masks:
                    # Sample small patch around candidate center
                    x0 = max(0, cx - margin)
                    x1 = min(width, cx + margin)
                    y0 = max(0, cy - margin)
                    y1 = min(height, cy + margin)
                    if em[y0:y1, x0:x1].any():
                        collision = True
                        break
                if collision:
                    continue

            return VoidGeometry(
                cx=cx, cy=cy,
                area_fraction=area_frac,
                shape=shape,
                contrast=contrast,
                edge_sigma=edge_sigma,
            )

        return None  # Could not place void without overlap
